name: Tic tac toe 
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Set-up Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci

      - name: Run tests
        run: npm run test

      - name: Deploy to GH pages
        uses: actions/deploy-pages@v2
        with:
          path: '.'
        env:
            GITHUB_TOKEN: ${{ secrets.TIC_REPO_TOKEN }}